---
jobs:
  - name: dcind
    public: true
    plan:
      - task: dcind
        privileged: true
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: dj80hd/dcind}
          run:
            path: /entrypoint.sh 
            args: [/docker-compose-ci-example/run.sh]
