---
resources:
  - name: resource-dcind
    type: git
    source:
      uri: https://github.com/dj80hd/docker-compose-ci-example
      branch: master
jobs:
  - name: dcind
    public: true
    plan:
      - get: resource-dcind
        trigger: true
      - task: dcind
        privileged: true
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: dj80hd/dcind}
          run:
            path: /entrypoint.sh 
            args: [/docker-compose-ci-example/run.sh]
